name: Scorecard supply-chain security

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
on:
  branch_protection_rule:
  schedule:
    - cron: '21 4 * * 1'
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Run analysis
        uses: ossf/scorecard-action@99c09fe975337306107572b4fdf4db224cf8e2f2
        with:
          results_file: scorecard-results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: SARIF file
          path: scorecard-results.sarif
          retention-days: 5

      - name: Upload to SARIF
        uses: github/codeql-action/upload-sarif@5e316336eb4f107009e477d4bfbfff13d7250fae
        with:
          sarif_file: scorecard-results.sarif
          category: OpenSSF Scorecard
